GET http://localhost:3001/api/persons

GET http://localhost:3001/info

GET http://localhost:3001/api/persons/10

GET http://localhost:3001/api/persons/1

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "viljami",
    "number": "0401587737"
}

GET https://puhelinluettelo-online.herokuapp.com/api/persons
